### PR TITLE
Server Report Card

### PR DESCRIPTION
**Pull request by schreiaj**
Adds a /:id/report_card route with a report card for each server. For tests that have not been run it will auto launch them otherwise it will navigate to the results of the tests. 

auto-launch

### CODE REVIEW

**Comment by radamson** [comment]
We should rebase this onto development before review/pulling.  https://github.com/siteadmin/inferno/pull/105 has changes that will impact this.

**Comment by schreiaj** [comment]
Rebased. @radamson

**Comment by radamson** [comment]
@schreiaj I made a few small changes to get this to work with the new way of handling sequences. 
 The salient change is that `sequences_groups` is no longer available on `SequenceBase` and are retrieved from associated module now.

**Comment by schreiaj** [comment]
Dang, Im gonna assume that there was some sort of weird cacheing thing going on with my browser that caused this to be missed by me :(

**Pull request closed without merging**
